mtime = 1678335343
[[pkgs]]
type = "github"
distrib = "fibbonaci-daerk"
package = "fibbonaci_daerk-0.0.1"
ext = "tar.gz"
sha256 = "d7633c3989443d98e47f261677068d9d90658c06d89879a9b66fe32d504d4362"
url = "https://api.github.com/repos/daerksun/pywharf-pkg-repo/releases/assets/98624163"

[pkgs.meta]
name = "fibbonaci-daerk"
version = "0.0.1"
filetype = "sdist"
pyversion = ""
metadata_version = "2.1"
summary = "Some test to run fibbonaci series"
home_page = ""
author = ""
author_email = "daerk <daerksun@gmail.com>"
maintainer = ""
maintainer_email = ""
license = ""
description = "# Esto\n## Es una\n### Prueba"
keywords = ""
classifiers = "License :: OSI Approved :: MIT License"
download_url = ""
comment = ""
sha256_digest = "d7633c3989443d98e47f261677068d9d90658c06d89879a9b66fe32d504d4362"
requires_python = ">=3.7"
description_content_type = "text/markdown"
md5_digest = "6e404f7b428de3e5a02778887ce2174c"
blake2_256_digest = "4e2d9c4347f48c43d374febc01799d2a09f1d575ee2cdc47dd87f94ade78169a"
":action" = "file_upload"
protocol_version = "1"
distrib = "fibbonaci-daerk"
sha256 = "d7633c3989443d98e47f261677068d9d90658c06d89879a9b66fe32d504d4362"
[[pkgs]]
type = "github"
distrib = "fibbonaci-daerk"
package = "fibbonaci_daerk-0.0.1-py3-none-any"
ext = "whl"
sha256 = "bdda0439b4b4f65e419d7eb7c3d3a2a66805c4700df9265e74219df61d5107dd"
url = "https://api.github.com/repos/daerksun/pywharf-pkg-repo/releases/assets/98624161"

[pkgs.meta]
name = "fibbonaci-daerk"
version = "0.0.1"
filetype = "bdist_wheel"
pyversion = "py3"
metadata_version = "2.1"
summary = "Some test to run fibbonaci series"
home_page = ""
author = ""
author_email = "daerk <daerksun@gmail.com>"
maintainer = ""
maintainer_email = ""
license = ""
description = "# Esto\n## Es una\n### Prueba"
keywords = ""
classifiers = "License :: OSI Approved :: MIT License"
download_url = ""
comment = ""
sha256_digest = "bdda0439b4b4f65e419d7eb7c3d3a2a66805c4700df9265e74219df61d5107dd"
requires_python = ">=3.7"
description_content_type = "text/markdown"
md5_digest = "7b73ccf0c834ba799ed66633e90535a9"
blake2_256_digest = "c0a244876911b34a004d18b252da2e6fe4c7c09a0f6252e57e82a2797ce0986d"
":action" = "file_upload"
protocol_version = "1"
distrib = "fibbonaci-daerk"
sha256 = "bdda0439b4b4f65e419d7eb7c3d3a2a66805c4700df9265e74219df61d5107dd"
